export {default as About} from './About'
export {default as Character} from './Character'
export {default as HomeLayout} from './HomeLayout'
export {default as Landing} from './Landing'
export {default as SinglePageError} from './SinglePageError'
export { default as Newsletter } from './Newsletter'
export { default as Card } from './Card'